name: no_try
description: Foundation for a exception-free approach to programing in Dart.
version: 1.0.0
homepage: https://www.github.com/xenoken/no_try
repository: https://www.github.com/xenoken/no_try
author: Ken Ekeoha <ekeohak@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
